name: Daily News Push
on:
  schedule:
    - cron: '0 8 * * *'  # 每天UTC时间0点（北京时间8点）
  workflow_dispatch:      # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      PYTHONUTF8: 1

    steps:
    # ========== 系统环境配置 ==========
    - name: 配置系统环境
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          locales \
          python3-dev \
          build-essential \
          cmake \
          protobuf-compiler \
          libprotobuf-dev

        # 配置UTF-8环境
        sudo locale-gen C.UTF-8
        sudo update-locale LANG=C.UTF-8

    # ========== Rust工具链配置 ==========
    - name: 安装Rust工具链
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        echo "[source.crates-io]" >> $HOME/.cargo/config
        echo "replace-with = 'rsproxy'" >> $HOME/.cargo/config
        echo "[source.rsproxy]" >> $HOME/.cargo/config
        echo "registry = \"https://rsproxy.cn/crates.io-index\"" >> $HOME/.cargo/config

    # ========== 代码检出 ==========
    - name: 检出代码
      uses: actions/checkout@v4

    # ========== Python环境配置 ==========
    - name: 设置Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    # ========== 依赖安装 ==========
    - name: 安装Python依赖
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install torch==2.5.0 \
          -f https://download.pytorch.org/whl/cpu \
          -i https://pypi.tuna.tsinghua.edu.cn/simple

        python3 -m pip install -r requirements.txt \
          --no-cache-dir \
          --force-reinstall \
          --use-pep517 \
          --global-option="--rust-extension" \
          -i https://pypi.tuna.tsinghua.edu.cn/simple \
          --extra-index-url https://pypi.org/simple

    # ========== 执行推送任务 ==========
    - name: 运行新闻推送
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python3 main.py
